CREATE TABLE COURSES 
(
  COURSE_ID NUMBER NOT NULL 
, COURSE_NAME VARCHAR2(20) 
, COURSE_START_DATE DATE 
, COURSE_DAYS NUMBER 
, COURSE_PRICE NUMBER 
, CONSTRAINT COURSES_PK PRIMARY KEY 
  (
    COURSE_ID 
  )
  ENABLE 
);

CREATE TABLE INSTRUCTORS 
(
  INSTRUCTOR_ID NUMBER NOT NULL 
, INSTRUCTOR_NAME VARCHAR2(40) 
, INSTRUCTOR_PHONE NUMBER 
, CONSTRAINT INSTRUCTORS_PK PRIMARY KEY 
  (
    INSTRUCTOR_ID 
  )
  ENABLE 
);

CREATE TABLE INVOICES 
(
  INVOICE_ID NUMBER NOT NULL 
, INVOICE_TOTAL NUMBER 
, PAYMENT_METHOD VARCHAR2(50) 
, INVOICE_NUMBER NUMBER NOT NULL 
, "Invoice_Status " VARCHAR2(100) 
, CONSTRAINT INVOICES_PK PRIMARY KEY 
  (
    INVOICE_ID 
  )
  ENABLE 
);

CREATE TABLE STUDENTS 
(
  STUDENT_ID NUMBER NOT NULL 
, STUDENT_NAME VARCHAR2(50) 
, STUDENT_AGE NUMBER 
, STUDENT_ADDRESS VARCHAR2(100) 
, STUDENT_WORK VARCHAR2(40) 
, STUDENT_PHONE NUMBER(*, 11) 
, STUDENT_COLLEGE VARCHAR2(20) 
, CONSTRAINT STUDENTS_PK PRIMARY KEY 
  (
    STUDENT_ID 
  )
  ENABLE 
);

CREATE TABLE STUDENT_COURSES 
(
  STUDENT_COURSES_ID NUMBER NOT NULL 
, CONSTRAINT STUDENT_COURSES_PK PRIMARY KEY 
  (
    STUDENT_COURSES_ID 
  )
  ENABLE 
);

CREATE VIEW VIEW1 AS SELECT 
 
FROM;

ALTER TABLE COURSES
ADD CONSTRAINT COURSES_INSTRUCTOR_FK FOREIGN KEY
(
  COURSE_ID 
)
REFERENCES INSTRUCTORS
(
  INSTRUCTOR_ID 
)
ON DELETE CASCADE ENABLE;

ALTER TABLE INVOICES
ADD CONSTRAINT INVOICES_STUDENTS_FK FOREIGN KEY
(
  INVOICE_ID 
)
REFERENCES STUDENTS
(
  STUDENT_ID 
)
ENABLE;

ALTER TABLE STUDENT_COURSES
ADD CONSTRAINT COURSES_FK FOREIGN KEY
(
  STUDENT_COURSES_ID 
)
REFERENCES COURSES
(
  COURSE_ID 
)
ENABLE;

ALTER TABLE STUDENT_COURSES
ADD CONSTRAINT STUDENTS_FK FOREIGN KEY
(
  STUDENT_COURSES_ID 
)
REFERENCES STUDENTS
(
  STUDENT_ID 
)
ENABLE;
